name: Generate Snake

on:
  schedule:
    # Cada 6 horas
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Actualiza la acción de checkout a la versión v3
      - uses: actions/checkout@v3

      # Crear el directorio de salida para evitar problemas
      - name: Create output directory
        run: mkdir -p dist

      # Generar la snake
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: GeekosServer
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Mostrar el estado del build para depuración
      - run: git status

      # Empujar los cambios a la rama principal
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          force: true

      # Publicar en GitHub Pages
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
